[package]
name = "MopaqPack-rs"
version = "0.1.0"
authors = ["Jai <814683@qq.com>"]
edition = "2018"

[dependencies]
ceres-mpq = {path = "libs/ceres-mpq"}

failure = "0.1.5"
clap = "2.33.0"
globwalk = "0.7.1"
serde_json = "1.0.40"

