[package]
name = "MopaqPack-rs"
version = "0.1.0"
authors = ["Jai <814683@qq.com>"]
edition = "2018"

[dependencies]
stormlib-sys = {path = "crates/stormlib-sys"}
stormlib = {path = "crates/stormlib"}

failure = "0.1.8"
clap = "2.33.1"
globwalk = "0.8.0"
serde_json = "1.0.56"

