[package]
name = "MopaqPack-rs"
version = "0.1.0"
authors = ["Jai <814683@qq.com>"]
edition = "2018"

[dependencies]
ceres-mpq = {path = "libs/ceres-mpq"}
storm-sys = {path = "libs/storm-sys"}

failure = "0.1.8"
clap = "2.33.1"
globwalk = "0.8.0"
serde_json = "1.0.56"

