edition = "2018"

unstable_features = true

# indent_style = "visual"
indent_style = "block"

merge_imports = false
reorder_imports = false
reorder_modules = false
reorder_impl_items = true

struct_field_align_threshold = 20
enum_discrim_align_threshold = 20

use_field_init_shorthand = true
overflow_delimited_expr = false